SELECT
    USER_ID, 
    NICKNAME, 
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER A JOIN USED_GOODS_BOARD B ON B.WRITER_ID = A.USER_ID
WHERE
    STATUS = 'DONE'
GROUP BY
    USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES