SELECT
    C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM
    ITEM_INFO AS A JOIN ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID
    JOIN ITEM_INFO AS C ON C.ITEM_ID = B.ITEM_ID
WHERE
    A.RARITY LIKE 'RARE'
ORDER BY
    ITEM_ID DESC