WITH A AS(
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN A USING(EMP_NO)
WHERE SCORE = (SELECT MAX(SCORE) FROM A)
ORDER BY SCORE DESC